server:
  port: 8021

spring:
  application:
    name: spring-dockerization
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #issue with swagger & actuator
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false