server:
  port: 8089
  servlet:
    context-path: /api

logging:
  level:
    root: WARN
    com.company: DEBUG
#    org:
#      springframework:
#        security: DEBUG
  file:
    name: "log-${spring.profiles.active}.txt"

management:
  endpoints:
    web:
      exposure:
        include: [ "env", "health", "info" ]

spring:
  application:
    name: ms-backend
  messages:
    basename: i18n/messages
    encoding: UTF-8
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
  datasource:
    url: "jdbc:postgresql://localhost:5431/test"
    username: "moon"
    password: "moon"
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

api:
  message: 'You are using ${spring.profiles.active} profile'

security:
  signingKey: "MaYzkSjmkzPC57L"
  realm: "test"
  resourceId: "ms-backend"
  clientId: "moon"
  clientSecret: "moon"